(ns aiueos.launcher-test
  "Real end-to-end proof for aiueos.launcher: writes a manifest EDN + a
  compiled .kotoba Wasm binary to a real temp directory, then drives them
  through `aiueos.launcher/verify-command`/`run-command`/`dispatch` exactly
  as a shell invocation of the CLI would -- genuine file I/O, not
  in-memory-only shortcuts."
  (:require [aiueos.launcher :as launcher]
            [aiueos.topic :as topic]
            [clojure.test :refer [deftest is testing]]
            #?(:clj [clojure.java.io :as io])
            #?(:clj [clojure.string :as str])))

;; Same fixture as aiueos.execute-test:
;; (ns demo-aiueos-execute-test)
;; (defn main [] (topic-publish 1 (i64 42)))
(def ^:private topic-publish-wasm-b64
  "AGFzbQEAAAABCwJgAn9+AX9gAAF/AhgBBmtvdG9iYQ10b3BpY19wdWJsaXNoAAADAgEBBQMBAAEG\nBwF/AUGAEAsHEQIEbWFpbgABBm1lbW9yeQIACgoBCABBAUIqEAAL")

#?(:clj
   (defn- temp-dir []
     (let [dir (java.nio.file.Files/createTempDirectory
                "aiueos-launcher-test" (make-array java.nio.file.attribute.FileAttribute 0))]
       (.toFile dir))))

#?(:clj
   (defn- write-fixtures!
     "Writes manifest.edn (+ optional policy.edn) and topic_publish.wasm
     into a fresh temp dir; returns
     {:manifest-path :policy-path :wasm-path}. MANIFEST is merged over a
     base manifest that declares :aiueos/wasm \"topic_publish.wasm\"
     (a path relative to the manifest file itself, per the launcher's
     resolve-wasm-path contract)."
     ([manifest] (write-fixtures! manifest nil))
     ([manifest policy-overlay]
      (let [dir (temp-dir)
            wasm-bytes (.decode (java.util.Base64/getDecoder)
                                 (str/replace topic-publish-wasm-b64 "\n" ""))
            wasm-file (io/file dir "topic_publish.wasm")
            manifest-file (io/file dir "manifest.edn")
            base {:aiueos/component :app/topic-publish :aiueos/kind :app
                  :aiueos/trust :verified :aiueos/wasm "topic_publish.wasm"
                  :aiueos/imports #{:topic/publish}}]
        (io/copy wasm-bytes wasm-file)
        (spit manifest-file (pr-str (merge base manifest)))
        (cond-> {:manifest-path (.getPath manifest-file) :wasm-path (.getPath wasm-file)}
          policy-overlay
          (assoc :policy-path
                 (let [policy-file (io/file dir "policy.edn")]
                   (spit policy-file (pr-str policy-overlay))
                   (.getPath policy-file))))))))

#?(:clj
   (deftest verify-command-reads-real-files-and-decides
     (let [{:keys [manifest-path]} (write-fixtures! {})
           result (launcher/verify-command manifest-path nil)]
       (is (= :grant (:aiueos/decision result)))
       (is (= :app/topic-publish (:aiueos/component result))))))

#?(:clj
   (deftest verify-command-denies-an-unresolved-import
     (let [{:keys [manifest-path]} (write-fixtures! {:aiueos/imports #{:custom/nobody-provides-this}})
           result (launcher/verify-command manifest-path nil)]
       (is (= :deny (:aiueos/decision result)))
       (is (= [:unresolved-capability] (mapv :aiueos/kind (:aiueos/violations result)))))))

#?(:clj
   (deftest run-command-reads-the-declared-wasm-path-and-really-executes
     (let [{:keys [manifest-path]} (write-fixtures! {})
           result (launcher/run-command manifest-path nil false)]
       (is (= :grant (:aiueos/decision result)))
       (is (= 0 (:aiueos.execute/result result)))
       (is (= 42 (topic/latest (:aiueos.execute/topic-bus result) 1))
           "the .kotoba component's own call really ran via Chicory, reading a real file off disk"))))

#?(:clj
   (deftest admit-command-floors-trust-before-running
     (testing ":aiueos/trust :trusted in the manifest is still floored to
     :ai-generated by admit -- an agent-submitted component can never
     claim its own trust"
       (let [{:keys [manifest-path]}
             (write-fixtures! {:aiueos/trust :trusted :aiueos/effects #{:network}})
             result (launcher/run-command manifest-path nil true)]
         (is (= :deny (:aiueos/decision result))
             ":network is forbidden for :ai-generated, even though the manifest claimed :trusted")
         (is (= [:forbidden-effect] (mapv :aiueos/kind (:aiueos/violations result))))))))

#?(:clj
   (deftest run-command-throws-when-manifest-declares-no-wasm
     (let [dir (temp-dir)
           manifest-file (io/file dir "no-wasm.edn")]
       (spit manifest-file (pr-str {:aiueos/component :app/x :aiueos/kind :app}))
       (is (thrown? clojure.lang.ExceptionInfo
                    (launcher/run-command (.getPath manifest-file) nil false))))))

#?(:clj
   (deftest dispatch-drives-verify-end-to-end-via-argv
     (let [{:keys [manifest-path]} (write-fixtures! {})
           out (java.io.StringWriter.)]
       (binding [*out* out]
         (launcher/dispatch ["verify" manifest-path "--edn"]))
       (let [printed (read-string (str/trim (str out)))]
         (is (= :grant (:aiueos/decision printed)))))))
