(ns aiueos.launcher-test
  "Real end-to-end proof for aiueos.launcher: writes a manifest EDN + a
  compiled .kotoba Wasm binary to a real temp directory, then drives them
  through `aiueos.launcher/verify-command`/`run-command`/`dispatch` exactly
  as a shell invocation of the CLI would -- genuine file I/O, not
  in-memory-only shortcuts."
  (:require [aiueos.audit :as audit]
            [aiueos.launcher :as launcher]
            [aiueos.topic :as topic]
            [clojure.test :refer [deftest is testing]]
            #?(:clj [clojure.java.io :as io])
            #?(:clj [clojure.string :as str])))

;; Same fixture as aiueos.execute-test:
;; (ns demo-aiueos-execute-test)
;; (defn main [] (topic-publish 1 (i64 42)))
(def ^:private topic-publish-wasm-b64
  "AGFzbQEAAAABCwJgAn9+AX9gAAF/AhgBBmtvdG9iYQ10b3BpY19wdWJsaXNoAAADAgEBBQMBAAEG\nBwF/AUGAEAsHEQIEbWFpbgABBm1lbW9yeQIACgoBCABBAUIqEAAL")

#?(:clj
   (defn- temp-dir []
     (let [dir (java.nio.file.Files/createTempDirectory
                "aiueos-launcher-test" (make-array java.nio.file.attribute.FileAttribute 0))]
       (.toFile dir))))

#?(:clj
   (defn- write-fixtures!
     "Writes manifest.edn (+ optional policy.edn) and topic_publish.wasm
     into a fresh temp dir; returns
     {:manifest-path :policy-path :wasm-path}. MANIFEST is merged over a
     base manifest that declares :aiueos/wasm \"topic_publish.wasm\"
     (a path relative to the manifest file itself, per the launcher's
     resolve-wasm-path contract)."
     ([manifest] (write-fixtures! manifest nil))
     ([manifest policy-overlay]
      (let [dir (temp-dir)
            wasm-bytes (.decode (java.util.Base64/getDecoder)
                                 (str/replace topic-publish-wasm-b64 "\n" ""))
            wasm-file (io/file dir "topic_publish.wasm")
            manifest-file (io/file dir "manifest.edn")
            base {:aiueos/component :app/topic-publish :aiueos/kind :app
                  :aiueos/trust :verified :aiueos/wasm "topic_publish.wasm"
                  :aiueos/imports #{:topic/publish}}]
        (io/copy wasm-bytes wasm-file)
        (spit manifest-file (pr-str (merge base manifest)))
        (cond-> {:manifest-path (.getPath manifest-file) :wasm-path (.getPath wasm-file)}
          policy-overlay
          (assoc :policy-path
                 (let [policy-file (io/file dir "policy.edn")]
                   (spit policy-file (pr-str policy-overlay))
                   (.getPath policy-file))))))))

#?(:clj
   (deftest verify-command-reads-real-files-and-decides
     (let [{:keys [manifest-path]} (write-fixtures! {})
           result (launcher/verify-command manifest-path nil)]
       (is (= :grant (:aiueos/decision result)))
       (is (= :app/topic-publish (:aiueos/component result))))))

#?(:clj
   (deftest verify-command-denies-an-unresolved-import
     (let [{:keys [manifest-path]} (write-fixtures! {:aiueos/imports #{:custom/nobody-provides-this}})
           result (launcher/verify-command manifest-path nil)]
       (is (= :deny (:aiueos/decision result)))
       (is (= [:unresolved-capability] (mapv :aiueos/kind (:aiueos/violations result)))))))

#?(:clj
   (deftest run-command-reads-the-declared-wasm-path-and-really-executes
     (let [{:keys [manifest-path]} (write-fixtures! {})
           result (launcher/run-command manifest-path nil false)]
       (is (= :grant (:aiueos/decision result)))
       (is (= 0 (:aiueos.execute/result result)))
       (is (= 42 (topic/latest (:aiueos.execute/topic-bus result) 1))
           "the .kotoba component's own call really ran via Chicory, reading a real file off disk"))))

#?(:clj
   (deftest admit-command-floors-trust-before-running
     (testing ":aiueos/trust :trusted in the manifest is still floored to
     :ai-generated by admit -- an agent-submitted component can never
     claim its own trust"
       (let [{:keys [manifest-path]}
             (write-fixtures! {:aiueos/trust :trusted :aiueos/effects #{:network}})
             result (launcher/run-command manifest-path nil true)]
         (is (= :deny (:aiueos/decision result))
             ":network is forbidden for :ai-generated, even though the manifest claimed :trusted")
         (is (= [:forbidden-effect] (mapv :aiueos/kind (:aiueos/violations result))))))))

#?(:clj
   (deftest run-command-throws-when-manifest-declares-no-wasm
     (let [dir (temp-dir)
           manifest-file (io/file dir "no-wasm.edn")]
       (spit manifest-file (pr-str {:aiueos/component :app/x :aiueos/kind :app}))
       (is (thrown? clojure.lang.ExceptionInfo
                    (launcher/run-command (.getPath manifest-file) nil false))))))

#?(:clj
   (deftest dispatch-drives-verify-end-to-end-via-argv
     (let [{:keys [manifest-path]} (write-fixtures! {})
           out (java.io.StringWriter.)]
       (binding [*out* out]
         (launcher/dispatch ["verify" manifest-path "--edn"]))
       (let [printed (read-string (str/trim (str out)))]
         (is (= :grant (:aiueos/decision printed)))))))

#?(:clj
   (deftest inspect-command-reads-a-system-file-and-its-components
     (let [dir (temp-dir)
           fs-manifest (io/file dir "fs.edn")
           app-manifest (io/file dir "app.edn")
           system-file (io/file dir "system.edn")]
       (spit fs-manifest (pr-str {:aiueos/component :service/fs :aiueos/kind :service
                                   :aiueos/exports #{:fs/read} :aiueos/imports #{}}))
       (spit app-manifest (pr-str {:aiueos/component :app/notes :aiueos/kind :app
                                    :aiueos/imports #{:fs/read} :aiueos/exports #{}}))
       (spit system-file (pr-str {:aiueos/system :demo :aiueos/components ["fs.edn" "app.edn"]}))
       (let [result (launcher/inspect-command (.getPath system-file))]
         (is (= :inspect (:aiueos.cli/command result)))
         (is (= [:service/fs] (get-in result [:aiueos/providers :fs/read])))
         (is (= 2 (count (:aiueos/depths result))))))))

#?(:clj
   (deftest surface-command-returns-the-offered-set-for-a-known-id
     (let [result (launcher/surface-command "robot")]
       (is (= :surface (:aiueos.cli/command result)))
       (is (contains? (:aiueos/offered result) :topic/publish)))))

#?(:clj
   (deftest surface-command-denies-an-unknown-id
     (let [result (launcher/surface-command "teapot")]
       (is (false? (:aiueos.cli/ok? result))))))

#?(:clj
   (deftest audit-command-reads-a-real-log-file-and-filters
     (let [dir (temp-dir)
           log-file (io/file dir "audit.edn")]
       (audit/append! log-file (audit/audit-entry :app/a :grant "caps: log/write" 1))
       (audit/append! log-file (audit/audit-entry :app/b :deny "unresolved" 2))
       (let [all (launcher/audit-command (.getPath log-file) nil nil)
             grants-only (launcher/audit-command (.getPath log-file) "grant" nil)]
         (is (= 2 (count (:aiueos/audit-events all))))
         (is (= 1 (count (:aiueos/audit-events grants-only))))
         (is (= :app/a (:aiueos/component (first (:aiueos/audit-events grants-only)))))))))

#?(:clj
   (deftest audit-command-reads-empty-when-log-file-does-not-exist
     (let [dir (temp-dir)
           result (launcher/audit-command (.getPath (io/file dir "no-such-log.edn")) nil nil)]
       (is (= [] (:aiueos/audit-events result))))))

#?(:clj
   (deftest dispatch-drives-surface-end-to-end-via-argv
     (let [out (java.io.StringWriter.)]
       (binding [*out* out]
         (launcher/dispatch ["surface" "--id" "robot" "--edn"]))
       (let [printed (read-string (str/trim (str out)))]
         (is (contains? (:aiueos/offered printed) :topic/publish))))))

;; ───────── up: multi-component boot orchestration ─────────

#?(:clj
   (defn- write-two-component-system!
     "A real 2-component system on disk: fs.edn (a pure capability
     provider, no :aiueos/wasm -- decision-only, matching verify-command's
     shape) and app.edn (imports :fs/read from fs AND declares
     :aiueos/wasm topic_publish.wasm -- ACTUALLY executes via
     aiueos.execute when up-command reaches it, exactly like
     run-command-reads-the-declared-wasm-path-and-really-executes above).
     Returns the system.edn path."
     [dir]
     (let [wasm-bytes (.decode (java.util.Base64/getDecoder)
                                (str/replace topic-publish-wasm-b64 "\n" ""))
           fs-manifest (io/file dir "fs.edn")
           app-manifest (io/file dir "app.edn")
           app-wasm (io/file dir "topic_publish.wasm")
           system-file (io/file dir "system.edn")]
       (spit fs-manifest (pr-str {:aiueos/component :service/fs :aiueos/kind :service
                                   :aiueos/exports #{:fs/read} :aiueos/imports #{}}))
       (io/copy wasm-bytes app-wasm)
       (spit app-manifest (pr-str {:aiueos/component :app/topic-publish :aiueos/kind :app
                                    :aiueos/trust :verified :aiueos/wasm "topic_publish.wasm"
                                    :aiueos/imports #{:fs/read :topic/publish} :aiueos/exports #{}}))
       (spit system-file (pr-str {:aiueos/system :demo :aiueos/components ["fs.edn" "app.edn"]}))
       (.getPath system-file))))

#?(:clj
   (deftest up-command-boots-a-provider-then-a-consumer-and-actually-executes-it
     (let [dir (temp-dir)
           system-path (write-two-component-system! dir)
           result (launcher/up-command system-path nil)]
       (is (true? (:aiueos.cli/ok? result)))
       (is (= 2 (count (:aiueos/boot-results result))))
       (is (= :service/fs (:aiueos/component (first (:aiueos/boot-results result))))
           "fs (the provider) boots before app (the consumer) -- boot-order, not declaration order, though here they're the same")
       (is (not (contains? (first (:aiueos/boot-results result)) :aiueos.execute/result))
           "fs has no :aiueos/wasm -- decision-only, like verify-command")
       (let [app-result (second (:aiueos/boot-results result))]
         (is (= :app/topic-publish (:aiueos/component app-result)))
         (is (= 42 (topic/latest (:aiueos.execute/topic-bus app-result) 1))
             "app DOES have :aiueos/wasm -- up-command actually executed it via Chicory")))))

#?(:clj
   (deftest up-command-stops-at-the-first-denied-component
     (let [dir (temp-dir)
           fs-manifest (io/file dir "fs.edn")
           app-manifest (io/file dir "app.edn")
           system-file (io/file dir "system.edn")]
       (spit fs-manifest (pr-str {:aiueos/component :service/fs :aiueos/kind :service
                                   :aiueos/exports #{:fs/read}
                                   :aiueos/imports #{:custom/nobody-provides-this}}))
       (spit app-manifest (pr-str {:aiueos/component :app/notes :aiueos/kind :app
                                    :aiueos/imports #{:fs/read} :aiueos/exports #{}}))
       (spit system-file (pr-str {:aiueos/system :demo :aiueos/components ["fs.edn" "app.edn"]}))
       (let [result (launcher/up-command (.getPath system-file) nil)]
         (is (false? (:aiueos.cli/ok? result)))
         (is (= :service/fs (:aiueos/stopped-at result)))
         (is (= 1 (count (:aiueos/boot-results result)))
             "app never even gets a boot attempt -- fs (its dependency) never came up")))))

#?(:clj
   (deftest up-command-reports-a-dependency-cycle-before-executing-anything
     (let [dir (temp-dir)
           a-manifest (io/file dir "a.edn")
           b-manifest (io/file dir "b.edn")
           system-file (io/file dir "system.edn")]
       (spit a-manifest (pr-str {:aiueos/component :app/a :aiueos/kind :app
                                  :aiueos/imports #{:b/thing} :aiueos/exports #{:a/thing}}))
       (spit b-manifest (pr-str {:aiueos/component :app/b :aiueos/kind :app
                                  :aiueos/imports #{:a/thing} :aiueos/exports #{:b/thing}}))
       (spit system-file (pr-str {:aiueos/system :demo :aiueos/components ["a.edn" "b.edn"]}))
       (let [result (launcher/up-command (.getPath system-file) nil)]
         (is (false? (:aiueos.cli/ok? result)))
         (is (= :graph/cycle (:aiueos.cli/code result)))
         (is (not (contains? result :aiueos/boot-results)))))))

#?(:clj
   (deftest dispatch-drives-up-end-to-end-via-argv
     (let [dir (temp-dir)
           system-path (write-two-component-system! dir)
           out (java.io.StringWriter.)]
       (binding [*out* out]
         (launcher/dispatch ["up" system-path "--edn"]))
       (let [printed (read-string (str/trim (str out)))]
         (is (true? (:aiueos.cli/ok? printed)))
         (is (= 2 (count (:aiueos/boot-results printed))))))))

;; ───────── up-command + ADR-0006 cycle-based scheduling ─────────

#?(:clj
   (defn- write-two-component-system-with-schedule!
     "Same fs/app system as write-two-component-system!, but app declares
     :aiueos/schedule {:period-ms 3 :cycle-ms 1} -- due only every 3rd
     cycle (0, 3, 6, ...). fs has no explicit schedule (default: due every
     cycle), matching a real system where an always-on capability
     provider coexists with a periodic consumer."
     [dir]
     (let [wasm-bytes (.decode (java.util.Base64/getDecoder)
                                (str/replace topic-publish-wasm-b64 "\n" ""))
           fs-manifest (io/file dir "fs.edn")
           app-manifest (io/file dir "app.edn")
           app-wasm (io/file dir "topic_publish.wasm")
           system-file (io/file dir "system.edn")]
       (spit fs-manifest (pr-str {:aiueos/component :service/fs :aiueos/kind :service
                                   :aiueos/exports #{:fs/read} :aiueos/imports #{}}))
       (io/copy wasm-bytes app-wasm)
       (spit app-manifest (pr-str {:aiueos/component :app/topic-publish :aiueos/kind :app
                                    :aiueos/trust :verified :aiueos/wasm "topic_publish.wasm"
                                    :aiueos/imports #{:fs/read :topic/publish} :aiueos/exports #{}
                                    :aiueos/schedule {:period-ms 3 :cycle-ms 1}}))
       (spit system-file (pr-str {:aiueos/system :demo :aiueos/components ["fs.edn" "app.edn"]}))
       (.getPath system-file))))

#?(:clj
   (deftest up-command-defaults-to-cycle-zero-booting-everyone
     (testing "no explicit cycle arg -- matches pre-scheduling up-command
     behavior exactly, since cycle 0 is due for every period"
       (let [dir (temp-dir)
             system-path (write-two-component-system-with-schedule! dir)
             result (launcher/up-command system-path nil)]
         (is (true? (:aiueos.cli/ok? result)))
         (is (= 2 (count (:aiueos/boot-results result))))))))

#?(:clj
   (deftest up-command-skips-a-component-not-due-this-cycle
     (testing "app's :period-ms 3 means it's due at cycles 0/3/6/...; at
     cycle 1 it's skipped, fs (default: due every cycle) still boots"
       (let [dir (temp-dir)
             system-path (write-two-component-system-with-schedule! dir)
             result (launcher/up-command system-path nil 1)]
         (is (true? (:aiueos.cli/ok? result)))
         (is (= 1 (count (:aiueos/boot-results result))))
         (is (= :service/fs (:aiueos/component (first (:aiueos/boot-results result)))))))))

#?(:clj
   (deftest up-command-boots-the-periodic-component-again-at-its-next-due-cycle
     (let [dir (temp-dir)
           system-path (write-two-component-system-with-schedule! dir)
           result (launcher/up-command system-path nil 3)]
       (is (true? (:aiueos.cli/ok? result)))
       (is (= 2 (count (:aiueos/boot-results result)))
           "cycle 3 is due for app again (period-cycles 3), fs is always due"))))

#?(:clj
   (deftest dispatch-drives-up-with-an-explicit-cycle-via-argv
     (let [dir (temp-dir)
           system-path (write-two-component-system-with-schedule! dir)
           out (java.io.StringWriter.)]
       (binding [*out* out]
         (launcher/dispatch ["up" system-path "--cycle" "1" "--edn"]))
       (let [printed (read-string (str/trim (str out)))]
         (is (= 1 (count (:aiueos/boot-results printed))))))))
